# need 4 gpus

project: pact
save_path: checkpoints
name: gsm-cot

only_eval: False

pact: False
cot: True
no_thoughts: False
no_cot: False

c_thought: 0
num_context_tokens: 2
projection_rank: 128
codebook_heads: 4
epochs_per_stage: 1
max_latent_stage: 0
pad_latent_to_max: True

# LoRA Configuration
use_lora: False
lora_r: 128
lora_alpha: 256
lora_dropout: 0.0
lora_target_modules: ["c_attn", "c_proj", "c_fc", "wte", "lm_head"] # GPT-2 specific modules.

save_only_improve: True
save_model: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: False
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 25
eval_frequency: 1
lr: !!float "1e-4"
weight_decay: 0.01
